# Classification approach

In [120]:
from warnings import simplefilter
from sklearn.decomposition import PCA
simplefilter(action='ignore', category=FutureWarning)
import pandas as pd
import numpy as np

In [129]:
df = pd.read_csv("Genotyped.csv", index_col='index')
output = pd.read_csv("Phenotypes.csv", index_col="index")

In [130]:
df['avg_phen'] = output['average phenotypes']

In [131]:
df.head(5)

,wPt.0538,wPt.8463,wPt.6348,wPt.9992,wPt.2838,wPt.8266,wPt.1100,wPt.0653,wPt.4418,wPt.2152,...,c.408294,c.408330,c.408336,c.408375,c.408393,c.408422,c.408424,c.408426,c.408443,avg_phen
index,,,,,,,,,,,,,,,,,,,,,
0,0,1,1,1,1,0,1,1,1,1,...,0,1,1,1,0,0,0,0,1,-0.648708
1,1,1,1,1,1,0,1,1,0,1,...,1,0,0,0,0,1,1,1,1,0.155402
2,1,1,1,1,1,0,1,1,0,1,...,1,0,0,0,0,1,1,1,1,-0.368790
3,0,1,1,1,1,0,1,1,1,1,...,1,1,1,0,0,1,0,1,0,0.483285
4,0,1,1,1,1,0,1,1,1,1,...,1,1,1,1,0,0,0,1,1,0.778173

In [150]:
print(output.sort_values('average phenotypes')[:1])
print(output.sort_values('average phenotypes')[-1:])

             V1        V2        V3        V4  average phenotypes
index
165   -2.224246 -2.527187 -2.267169 -1.842812           -2.339534
             V1        V2        V3        V4  average phenotypes
index
446   -0.894342  1.409251  4.875385 -0.668887            1.796764

So, we know that the lowest avg phenotype is -2.~<br/>
And the highest avg phenotype is 1.79~

In [ ]:
step = ()